
#   Copyright 2016 Cisco Systems
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


# this section describes general setting for taxii log adapter
# pollEndpoint is address of taxii server located in cisco cloud
# username and password are credentials for data export account
# and can be obtained through your CTA GUI under menu-CTA STIX/TAXII API
# feeds is list of TAXII feeds, one collection for most cases and
# the collection name you have received with the credentials
# for detailed feeds configuration please see
# https://github.com/CiscoCTA/taxii-log-adapter/wiki/Configuration#taxii-feed

# Strings "user", "pass" and "collection_name" you have to replace with valid ones from your CTA account

taxiiService:
    pollEndpoint: https://taxii.cloudsec.sco.cisco.com/skym-taxii-ws/PollService/
    username: user
    password: pass
    feeds:
        - collection_name

# schedule section contains cron-like expression
# meaning of asterisk are second, minute, hour, day, month, weekday
# configuration is also described on wiki
# https://github.com/CiscoCTA/taxii-log-adapter/wiki/Configuration#scheduling

schedule:
    cron: "0 0 * * * *"

# transform section contains path to xsl template that is applied to STIX downloaded data
# please uncomment line with data format corresponding to your SIEM

transform:
# json format suitable for SPLUNK
#    stylesheet: config/stix2json.xsl

# cef format suitable for ArcSigh/Logpoint
#    stylesheet: config/stix2cef.xsl

# blank transformation that allows storing raw downloaded data
#    stylesheet: config/stix2stix.xsl

# The application uses the same logback configuration file to configure also its own logging.
logging:
    config: config/logback.xml

# Uncomment the following lines to use HTTP proxy when performing TAXII requests

# proxy:
#    url: http://localhost:8002/
#    authenticationType: basic
#    username: user
#    password: pass
